COMPUTER_VISION_SUBSCRIPTION_KEY: 
COMPUTER_VISION_ENDPOINT: 

CUSTOM_VISION_PROJECT_ID: 

# prediction
CUSTOM_VISION_ENDPOINT: 
CUSTOM_VISION_PREDICTION_KEY: 
CUSTOM_VISION_RESOURCE_ID: 

# training
CUSTOM_VISION_TRAINING_KEY: 
CUSTOM_VISION_ENDPOINT: 
CUSTOM_VISION_ITERATION_ID: 

# Application
WATCH_FOLDER: