# Project ID
CUSTOM_VISION_PROJECT_ID:
CUSTOM_VISION_ITERATION_ID:

# prediction
CUSTOM_VISION_ENDPOINT:
CUSTOM_VISION_PREDICTION_KEY:
CUSTOM_VISION_RESOURCE_ID:

# Application
WATCH_FOLDER: /Users/steve/cats/test
NUMBER_PHOTOS_IN_SET: 5
TIMOUT: 15
